version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      expo:
        patterns:
          - "expo"
          - "expo-*"
          - "@expo/*"
      react-native:
        patterns:
          - "react-native"
          - "react-native-*"
          - "@react-native/*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
